# Generated by Django 4.0.4 on 2022-05-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sweetwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.CharField(help_text='The salt that we will use in the users account', max_length=128)),
                ('sweetwords', models.CharField(help_text='all the sweetwords including the real and alla the fake', max_length=65536)),
            ],
            options={
                'verbose_name_plural': 'sweetwords',
            },
        ),
    ]
